### PR TITLE
Admin can put any file in a collection

### PR DESCRIPTION
**Pull request by criedlberger**

### CODE REVIEW

**Comment by pgwillia** [comment]
4) collection show collection as admin should show a theses collection
     Failure/Error: Unable to find matching line from backtrace
     ActionView::Template::Error:
       undefined local variable or method `dashboard_all_path' for #<#<Class:0x007fee74105cd8>:0x007fee7f88bec0>
     # ./app/views/my/index.html.erb:27:in `_app_views_my_index_html_erb___4303127735363824295_54414940'

Also seeing this in the UI.

**Comment by pgwillia** [comment]
New observation from UI.  Batch uploading by non-admin user 

```
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"generic_files", :format=>nil, :id=>#<SolrDocument:0x00000008a2cd50 @_source={"system_create_dtsi"=>"2015-02-26T17:24:45Z", "system_modified_dtsi"=>"2015-02-26T17:25:10Z", "active_fedora_model_ssi"=>"GenericFile", "has_model_ssim"=>["GenericFile"], "id"=>"fa46763d-efa6-4351-8e34-e0baf814aa73", "object_profile_ssm"=>["{\"id\":\"fa46763d-efa6-4351-8e34-e0baf814aa73\",\"mime_type\":\"image/jpeg\",\"format_label\":[\"JPEG File Interchange Format\"],\"file_size\":[\"845941\"],\"last_modified\":[\"2015:02:26 10:24:48-07:00\"],\"filename\":[\"Desert.jpg\"],\"original_checksum\":[\"ba45c8f60456a672e003a875e469d0eb\"],\"rights_basis\":[],\"copyright_basis\":[],\"copyright_note\":[],\"well_formed\":[],\"valid\":[],\"status_message\":[],\"file_title\":[],\"file_author\":[],\"page_count\":[],\"file_language\":[],\"word_count\":[],\"character_count\":[],\"paragraph_count\":[],\"line_count\":[],\"table_count\":[],\"graphics_count\":[],\"byte_order\":[],\"compression\":[\"JPEG (old-style)\"],\"color_space\":[],\"profile_name\":[],\"profile_version\":[],\"orientation\":[],\"color_map\":[],\"image_producer\":[],\"capture_device\":[],\"scanning_software\":[],\"exif_version\":[],\"gps_timestamp\":[],\"latitude\":[],\"longitude\":[],\"character_set\":[],\"markup_basis\":[],\"markup_language\":[],\"bit_depth\":[],\"channels\":[],\"data_format\":[],\"offset\":[],\"frame_rate\":[],\"label\":\"Desert.jpg\",\"depositor\":\"tricia.jenkins@ualberta.ca\",\"relative_path\":\"\",\"import_url\":null,\"part_of\":[],\"resource_type\":[],\"title\":[\"Desert.jpg\"],\"creator\":[\"tricia.jenkins@ualberta.ca\"],\"contributor\":[],\"description\":[],\"tag\":[],\"rights\":[],\"publisher\":[],\"date_created\":[],\"date_uploaded\":\"2015-02-26\",\"date_modified\":\"2015-02-26\",\"subject\":[],\"language\":[],\"identifier\":[],\"based_near\":[],\"related_url\":[],\"bibliographic_citation\":[],\"source\":[],\"proxy_depositor\":null,\"on_behalf_of\":null,\"batch_id\":\"ddfcb675-c9aa-4d53-9d58-1a221747fb9b\"}"], "identification_identity_mime_type_tesim"=>["image/jpeg"], "identification_0_identity_0_mime_type_tesim"=>["image/jpeg"], "mime_type_tesim"=>["image/jpeg"], "isPartOf_ssim"=>["ddfcb675-c9aa-4d53-9d58-1a221747fb9b"], "depositor_ssim"=>["tricia.jenkins@ualberta.ca"], "depositor_tesim"=>["tricia.jenkins@ualberta.ca"], "title_tesim"=>["Desert.jpg"], "creator_tesim"=>["tricia.jenkins@ualberta.ca"], "date_uploaded_dtsi"=>"2015-02-26T00:00:00Z", "date_modified_dtsi"=>"2015-02-26T00:00:00Z", "label_tesim"=>["Desert.jpg"], "file_format_tesim"=>["jpeg (JPEG File Interchange Format)"], "edit_access_person_ssim"=>["tricia.jenkins@ualberta.ca"], "timestamp"=>"2015-02-26T17:25:11.309Z", "score"=>1.0}, @solr_response=nil, @export_formats={:xml=>{:content_type=>"application/xml"}, :dc_xml=>{:content_type=>"text/xml"}, :oai_dc_xml=>{:content_type=>"text/xml"}}, @m=#<GenericFile id: "fa46763d-efa6-4351-8e34-e0baf814aa73", mime_type: "image/jpeg", format_label: ["JPEG File Interchange Format"], file_size: ["845941"], last_modified: ["2015:02:26 10:24:48-07:00"], filename: ["Desert.jpg"], original_checksum: ["ba45c8f60456a672e003a875e469d0eb"], rights_basis: [], copyright_basis: [], copyright_note: [], well_formed: [], valid: [], status_message: [], file_title: [], file_author: [], page_count: [], file_language: [], word_count: [], character_count: [], paragraph_count: [], line_count: [], table_count: [], graphics_count: [], byte_order: [], compression: ["JPEG (old-style)"], color_space: [], profile_name: [], profile_version: [], orientation: [], color_map: [], image_producer: [], capture_device: [], scanning_software: [], exif_version: [], gps_timestamp: [], latitude: [], longitude: [], character_set: [], markup_basis: [], markup_language: [], bit_depth: [], channels: [], data_format: [], offset: [], frame_rate: [], label: "Desert.jpg", depositor: "tricia.jenkins@ualberta.ca", relative_path: "", import_url: nil, part_of: [], resource_type: [], title: ["Desert.jpg"], creator: ["tricia.jenkins@ualberta.ca"], contributor: [], description: [], tag: [], rights: [], publisher: [], date_created: [], date_uploaded: "2015-02-26", date_modified: "2015-02-26", subject: [], language: [], identifier: [], based_near: [], related_url: [], bibliographic_citation: [], source: [], proxy_depositor: nil, on_behalf_of: nil, batch_id: "ddfcb675-c9aa-4d53-9d58-1a221747fb9b", embargo_id: nil, lease_id: nil>>} missing required keys: [:id]):
    13:   </td>
    14:   <td>
    15:     <div class="media">
    16:       <%= link_to sufia.generic_file_path(document), class: "pull-left", "aria-hidden" => true do %>
    17:         <%= render_thumbnail_tag document, { class: "hidden-xs file_listing_thumbnail" }, { suppress_link: true } %>
    18:       <% end %>
    19:       <div class="media-body">
  app/views/my/index.html.erb:35:in `_app_views_my_index_html_erb__2980712293928593904_25608780'
```

**Comment by pbinkley** [comment]
@criedlberger , I think you can clean up the user name by just adding the right forms of your email address to your account, at https://github.com/settings/emails . It looks like your account uses criedlberger@ualberta.ca, but your most recent commit went in as christian.riedlberger@ualberta.ca and your earlier commits went as criedlbe@DIG002CR1.ualibrary.ualberta.ca . If you add those two addresses to your Github account, everything will be attributed to you and the history will be clean. I've rebased this PR and I'm going to merge it now.

**Comment by pgwillia** [comment]
@pbinkley When I was looking at this earlier, I pointed out that @criedlberger had missed adding a template which allows the admin to actually add files to a collection from the UI.  I think he's working on that now.

**Comment by pbinkley** [comment]
@pgwillia @criedlberger  Ah, sorry, I took it that all that was resolved. Let me know when it's ready.

**Comment by pgwillia** [comment]
Selected file from http://hydranorth.local/dashboard/all and clicked on 'Add to Collection' resulted in

NoMethodError in CollectionsController#update
undefined method `normalize_identifier' for #<CollectionsController:0x007f51cc7864f8>

Also would be nice to have selenium or capybara test which asserts that what was demoed works to catch potential future regresssions.

**Comment by pgwillia** [comment]
https://github.com/projecthydra/sufia/commit/b21ec923b475f033bb824d6bd48ac3b6d5405abd is where normalize_identifier was removed.

**Comment by criedlberger** [comment]
Changed file to remove normalize_identifier, ready to merge

**Pull request merged**
