### PR TITLE
Add reset-all and restart-all scripts (based on README.md instructions)

### PR DESCRIPTION
**Pull request by pbinkley**
I've added two scripts in the bin directory, reset-all and restart-all, incorporating Tricia's instructions in README.md. This makes it easier to run the multistep processes without missing anything.

### CODE REVIEW

**Comment by pgwillia** [comment]
Looks good!  Could you update the README.md to refer to the scripts?  Then I think it's ready for merge.

**Comment by pgwillia** [comment]
This isn't a deficiency with the scripts, but with a deficiency with the resque-pool service.  If /var/www/sites/tmp/pids/resque-pool.pid doesn't exist (like when you run the vagrant provisioning step to change the git working directory) but resque is already running you'll end up with extra (and old) resque workers:
```
[root@hydranorth hydranorth]# ps aux | grep resque
root      4772  0.2  6.9 331280 133988 ?       Sl   09:29   0:03 resque-pool-master[hydranorth]: managing [4832, 4835, 4838]
root      4832  0.0  7.0 333848 134724 ?       Sl   09:30   0:00 resque-1.25.2:   Waiting for *
root      4835  0.0  7.0 333864 134748 ?       Sl   09:30   0:00 resque-1.25.2:   Waiting for *
root      4838  0.0  7.0 334004 134808 ?       Sl   09:30   0:00 resque-1.25.2:   Waiting for *
root      4997  3.2  6.9 331424 134116 ?       Sl   09:51   0:02 resque-pool-master[hydranorth]: managing [5092, 5095, 5098]
root      5092  0.0  6.8 331424 132208 ?       Sl   09:51   0:00 resque-1.25.2:   Waiting for *
root      5095  0.0  6.8 331424 132216 ?       Sl   09:51   0:00 resque-1.25.2:   Waiting for *
root      5098  0.0  6.8 331424 132216 ?       Sl   09:51   0:00 resque-1.25.2:   Waiting for *
root      5149  0.0  0.0 103248   876 pts/0    S+   09:52   0:00 grep resque
```

The only way I know of to clear these is  
```
kill -9  `ps aux | grep [r]esque | grep -v grep | cut -c 10-16`
service resque-pool start
```

**Comment by pbinkley** [comment]
I was just going to change my "bin/rake" calls to "bundle exec rake" -
that's the correct method, isn't it? I'll do the README as well.

**Comment by pgwillia** [comment]
I think bundle exec rake would work in the most situations. Both are correct.

bin/rake assumes that the version of rake that your application invokes is installed as a system gem.  bundle exec rake will invoke the version of rake that your application depends on.

**Pull request merged**
