### PR TITLE
Migration script fix

### PR DESCRIPTION
**Pull request by weiweishi**
Changes included:
* changed date_modified to last modified time of the object instead of the migration time
* handles the date fields correctly by converting them from string to DateTime
* add collection title to hasCollection in GenericFile
* handle multiple creators/contributors correctly by using xpath instead of at_xpath.
* only active/non-deleted objects from ERA will be migrated (only those files will be selected).

### CODE REVIEW

**Comment by weiweishi** [comment]
address #251

**Comment by pgwillia** [comment]
Where can I find data to test these changes with?

I'd like to modify the commits so that there is one each for:
* changed date_modified to last modified time of the object instead of the migration time fixes #267
* handles the date fields correctly by converting them from string to DateTime fixes #271 
* add collection title to hasCollection in GenericFile fixes #274
* handle multiple creators/contributors correctly by using xpath instead of at_xpath.
* handle special reports fixes #251
* only active/non-deleted objects from ERA will be migrated (only those files will be selected).
 * also add documentation to README or rake task regarding included/excluded files

**Comment by weiweishi** [comment]
Test data is at lib/tasks/migration/test-metadata. I can work on these
clean-up work as you may need to spend time reading/undestanding my code.

Thanks!

**Comment by pbinkley** [comment]
Larger data sets from the previous migration run were on Plano, but I can't log into Plano now (rejecting my certificate - I'll let Henry know). Could we put a current set of migration data in the shared drive, so anyone can use it for testing?

**Comment by anayram** [comment]
Migrated data versions are available at the DI shared drive in directory
Hydra_DAMS\ERA\ERA migration\FOXML transformed

**Comment by pgwillia** [comment]
I'm getting an error when running ```rake migration:eraitem['lib/tasks/migration/test-metadata/metadata']```

```
FAILED: Item uuid:e4527566-67c1-4f56-8ca8-f94e2e760e09 migration!
no implicit conversion of nil into String
["/var/www/sites/hydranorth/lib/tasks/migration.rake:372:in `strptime'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:372:in `block in migrate_object'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:201:in `glob'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:201:in `migrate_object'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:99:in `block (2 levels) in <top (required)>'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'", "/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'", "/usr/bin/rake:33:in `<main>'"]
```

**Comment by weiweishi** [comment]
Replaced this PR with PR #281

**Pull request closed without merging**
