### PR TITLE
Ark feature branch

### PR DESCRIPTION
**Pull request by criedlberger**
Make sure to restart application when making changes to the EZID service

### CODE REVIEW

**Comment by pbinkley** [comment]
I deployed a new vm and used bin/restart-all, and I'm still getting an error from Resque when I upload a file:

```
Exception
    NoMethodError
Error
    undefined method `gsub' for nil:NilClass

    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/metadata.rb:125:in `escape'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/metadata.rb:66:in `block in to_anvl'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/metadata.rb:65:in `each'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/metadata.rb:65:in `map'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/metadata.rb:65:in `to_anvl'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/requests/request.rb:123:in `add_metadata'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/requests/request.rb:95:in `block in get_response_for_request'
    /usr/lib64/ruby/2.1.0/net/http.rb:853:in `start'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/requests/request.rb:93:in `get_response_for_request'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/requests/request.rb:51:in `execute'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/requests/request.rb:30:in `execute'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/client.rb:210:in `execute'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/client.rb:144:in `modify_identifier'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/identifier.rb:217:in `modify'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/identifier.rb:234:in `persist'
    /usr/lib64/ruby/gems/2.1.0/gems/ezid-client-1.2.0/lib/ezid/identifier.rb:84:in `save'
    /var/www/sites/hydranorth/app/services/hydranorth/ezid_service.rb:31:in `create'
    /var/www/sites/hydranorth/app/jobs/batch_update_job.rb:82:in `update_file'
    /var/www/sites/hydranorth/app/jobs/batch_update_job.rb:35:in `block in run'
    /usr/lib64/ruby/gems/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/delegation.rb:16:in `each'
    /usr/lib64/ruby/gems/2.1.0/gems/active-fedora-9.4.2/lib/active_fedora/relation/delegation.rb:16:in `each'
    /var/www/sites/hydranorth/app/jobs/batch_update_job.rb:34:in `run'
    /usr/lib64/ruby/gems/2.1.0/gems/sufia-models-6.2.0/lib/sufia/models/resque.rb:32:in `perform'
```

**Comment by criedlberger** [comment]
@pbinkley Seeding batchuser has been removed from this branch. I added that back without any other changes and arks are being created.

**Comment by weiweishi** [comment]
I've also merged @pbinkley's PR to master, so if you get the latest master
it should have the change.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
Argh, I should have thought of that. I'll merge master and test again.

**Comment by pbinkley** [comment]
Note: can't be deployed in production until #957 is done. But the development work is finished.

**Pull request merged**
