### PR TITLE
Added facet fixes

### PR DESCRIPTION
**Pull request by criedlberger**

### CODE REVIEW

**Comment by pbinkley** [comment]
This PR includes some of the deployment changes to config files (e.g. replacing the empty tokens in config/initializers/sufia.rb with the actual noids of the CSTR and SER collections). These files need to be put back to their undeployed state. I'm not sure if there are actual changes, though, that need to be kept. It also includes some changes to the Gemfile.lock that I'm not sure about (removing clamav must be wrong, but I'm not sure about the version change in the BUNDLED WITH section).

**Comment by pbinkley** [comment]
Only thing left is the "is part of" link at the top of the display. On a community, this should be removed (since there's nothing for it to be part of); on a collection, it should show the community title as a link as in @sfbetz 's screenshot in https://docs.google.com/presentation/d/195k-GIB4C2W7KFrqna6XMki8IGxvWaZx_HGBXZSYzh8/edit#slide=id.p
Current state: 
962-collection

**Comment by leahvanderjagt** [comment]
Whoops, sorry I didn't notice that, Chris.

On Thu, May 5, 2016 at 10:29 AM, Peter Binkley <notifications@github.com>
wrote:

> Only thing left is the "is part of" link at the top of the display. On a
> community, this should be removed (since there's nothing for it to be part
> of); on a collection, it should show the community title as a link as in
> @sfbetz <https://github.com/sfbetz> 's screenshot in
> https://docs.google.com/presentation/d/195k-GIB4C2W7KFrqna6XMki8IGxvWaZx_HGBXZSYzh8/edit#slide=id.p
> Current state:
> [image: 962-collection]
> <https://cloud.githubusercontent.com/assets/272816/15049585/337bc1ac-12ac-11e6-93f2-66c7f5725fa6.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/pull/1082#issuecomment-217202279>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
This doesn't fix the problem for me: I still see things as in the screenshot above, both at the collection and community level. @criedlberger

**Comment by pbinkley** [comment]
Here's my test community and collection:

Namespace:

```
PREFIX ns001: <info:fedora/fedora-system:def/model#>
PREFIX ns004: <http://purl.org/dc/terms/>
PREFIX ns006: <http://terms.library.ualberta.ca/identifiers/>
PREFIX ns008: <info:fedora/fedora-system:def/relations-external#>
```

Collection:

```
 ns001: hasModel
    Collection 
ns004: title
    Research Reports 
ns006: is_admin_set
    false 
ns006: is_community
    false 
ns006: is_official
    true 
ns006: belongsToCommunity
    0v8380566 
```

Community:

```
 ns001: hasModel
    Collection 
ns004: title
    ACCES Research Group 
ns006: is_admin_set
    false 
ns006: is_community
    true 
ns006: is_official
    true 
ns008: hasCollectionMember
    4j03cz64w 
```

**Comment by pbinkley** [comment]
@criedlberger  Here are the namespace differences I found between this branch and master:

New collection in my dev environment on this branch:

```
PREFIX ns002: <http://terms.library.ualberta.ca/>
ns002: belongsToCommunity
    1c18df763 
```

collection in production environment:

```
PREFIX ns002: <http://terms.library.library.ca/identifiers/>
ns002: belongsToCommunity
    44558r36x
```

I only looked at the belongsToCommunity property.

**Pull request closed without merging**
