### PR TITLE
Embargo sufia6

### PR DESCRIPTION
**Pull request by weiweishi**
The old embargo branch has been removed. Changes in the new version of Hydrahead and Sufia had some impact on the embargo code. I've rewritten some of them and retested it. Now here is the new branch and new pull request. 

Weiwei

### CODE REVIEW

**Comment by pbinkley** [comment]
Weiwei, I'm afraid I'm still getting three failed tests (see below). Do you see these? If not, maybe next week we could talk about my environment and see what I'm missing.

```
[root@hydranorth hydranorth]# bundle exec rake spec
/usr/bin/ruby -I/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rspec-core-3.1.7/lib:/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rspec-support-3.1.2/lib /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
...........FF.F.

Failures:

  1) coauthor abby shares work @ included
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in "Hydra North click for notifications. click for archivist1@example.com dashboard Home About Help Contact Search Sufia Go All × The file little_file.txt has been updated. My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Permissions Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to until then Private Visible to users/groups specified below, if any. Share With (optional) Enter Account Label (one at a time)Use the add button to give access to one Account Label at a time (it will be added to the list below). Select the user, by name or Account Label. Then select the access level you wish to grant and click on Add this Account Label to complete adding the permission.Account Label (without the @ualberta.ca part) Search for a user Account Label (without the @ualberta.ca part)Access type to grantAdd this Account Label Use the add button to give access to one group at a time (it will be added to the list below).GroupAccess type to grantAdd this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save A service of Project Hydra. v.6.0.0.rc1 Copyright © 2013 Project Hydra Licensed under the Apache License, Version 2.0 Background image courtesy of Penn State University"
     # ./spec/features/coauthor_spec.rb:74:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:34:in `block (3 levels) in <top (required)>'

  2) coauthor abby shares work @ not included
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in "Hydra North click for notifications. click for archivist1@example.com dashboard Home About Help Contact Search Sufia Go All × The file little_file.txt has been updated. My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Permissions Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to until then Private Visible to users/groups specified below, if any. Share With (optional) Enter Account Label (one at a time)Use the add button to give access to one Account Label at a time (it will be added to the list below). Select the user, by name or Account Label. Then select the access level you wish to grant and click on Add this Account Label to complete adding the permission.Account Label (without the @ualberta.ca part) Search for a user Account Label (without the @ualberta.ca part)Access type to grantAdd this Account Label Use the add button to give access to one group at a time (it will be added to the list below).GroupAccess type to grantAdd this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save A service of Project Hydra. v.6.0.0.rc1 Copyright © 2013 Project Hydra Licensed under the Apache License, Version 2.0 Background image courtesy of Penn State University"
     # ./spec/features/coauthor_spec.rb:74:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:38:in `block (3 levels) in <top (required)>'

  3) coauthor abby shares work barbara can edit and feature
     Failure/Error: expect(page).to have_content( user.email )
       expected to find text "dit.application.test@ualberta.ca" in "Hydra North click for notifications. click for archivist1@example.com dashboard Home About Help Contact Search Sufia Go All × The file little_file.txt has been updated. My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Permissions Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to until then Private Visible to users/groups specified below, if any. Share With (optional) Enter Account Label (one at a time)Use the add button to give access to one Account Label at a time (it will be added to the list below). Select the user, by name or Account Label. Then select the access level you wish to grant and click on Add this Account Label to complete adding the permission.Account Label (without the @ualberta.ca part) Search for a user Account Label (without the @ualberta.ca part)Access type to grantAdd this Account Label Use the add button to give access to one group at a time (it will be added to the list below).GroupAccess type to grantAdd this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save A service of Project Hydra. v.6.0.0.rc1 Copyright © 2013 Project Hydra Licensed under the Apache License, Version 2.0 Background image courtesy of Penn State University"
     # ./spec/features/coauthor_spec.rb:74:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:50:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 47.4 seconds (files took 7.82 seconds to load)
16 examples, 3 failures

Failed examples:

rspec ./spec/features/coauthor_spec.rb:32 # coauthor abby shares work @ included
rspec ./spec/features/coauthor_spec.rb:36 # coauthor abby shares work @ not included
rspec ./spec/features/coauthor_spec.rb:48 # coauthor abby shares work barbara can edit and feature
/usr/bin/ruby -I/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rspec-core-3.1.7/lib:/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rspec-support-3.1.2/lib /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by weiweishi** [comment]
Those failed tests are coauthor spec tests. I think both I and Tricia see
them occasionally - with or without my embargo tests (although I was seeing
email already existed error message). We had a chat about this but I didn't
have a chance to take a closer look. I will look into it next week,
although I think these are unrelated issues.

**Comment by pbinkley** [comment]
Ah, OK. I should have noticed that. Since they're unrelated I'll merge the
PR now.

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
Not sure why Github says there are unmerged commits: I've merged the branch into master and committed it. I'll leave the branch open until we have a chance to check this next week.

**Comment by pgwillia** [comment]
I haven't seen this particular failure. I did see the embargo changes
causing regressions to the coauthor spec. Before calling this done, I'd
address why these tests that previously passed are now failing.

**Comment by pbinkley** [comment]
Those same three tests passed on @pgwillia 's PR just now when I tested it
on its own, but failed when I merged master into it (which would bring in
the changes from the embargo PR). Let's sort this out next week.

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
Checked out the commit prior to the embargo merge :17b32e93800ae2d7ed36229ef0fcea7e39966e50
The same three tests still failed but with different error message this time:

 1) coauthor abby shares work @ included
     Failure/Error: click_link "Permissions"
     Capybara::ElementNotFound:
       Unable to find link "Permissions"
     # ./spec/features/coauthor_spec.rb:73:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:34:in `block (3 levels) in <top (required)>'

  2) coauthor abby shares work @ not included
     Failure/Error: click_link "Permissions"
     Capybara::ElementNotFound:
       Unable to find link "Permissions"
     # ./spec/features/coauthor_spec.rb:73:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:38:in `block (3 levels) in <top (required)>'

  3) coauthor abby shares work barbara can edit and feature
     Failure/Error: click_link "Permissions"
     Capybara::ElementNotFound:
       Unable to find link "Permissions"
     # ./spec/features/coauthor_spec.rb:73:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:50:in `block (3 levels) in <top (required)>'

**Pull request closed without merging**
