### PR TITLE
Browse functionality.

### PR DESCRIPTION
**Pull request by nnunn**

### CODE REVIEW

**Comment by weiweishi** [comment]
Seeing the following error message after checking out the browseux branch - have restarted with bin/restart_all. 
image

**Comment by nnunn** [comment]
Did restart all work? I have a feeling this is because there is more
records than I am working with. I will dig into it.

**Comment by nnunn** [comment]
Ok that bug is now fixed.

**Comment by weiweishi** [comment]
Looks good @nnunn. One thing though:
For the Item Type, only the first item type shows in the list, is it possible to make it populate with more item types? example: http://plano.library.ualberta.ca/browse
image

**Comment by nnunn** [comment]
ahh sorry - I was using less results so I could test it...

That fix is committed and pushed now.

**Comment by nnunn** [comment]
wait it's not up yet. 2 minutes.

**Comment by nnunn** [comment]
Ok that fix is up now.

**Comment by weiweishi** [comment]
Thank you!

**Pull request merged**
