### PR TITLE
Uxdesign

### PR DESCRIPTION
**Pull request by nnunn**
Basic UX Design for ERA (aka HydraNorth). Much usability work still required, but this is a good start.

Still to do:
1) responsive css queries for mobile version
2) make sure design works with data
3) Individualized collections pages

### CODE REVIEW

**Comment by pgwillia** [comment]
Many of the tests are failing because of a javascript error on the page that is unrelated to the functionality in the test.

```CanvasJS Error: Chart Container with id "chartContainer" was not found```

Options are 
1. fix the javascript error @nnunn how hard would that be?
2. have the driver ignore js errors
```
diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
index 937cc68..75bd040 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -127,3 +127,6 @@ module FactoryGirl
   end
 end

+Capybara.register_driver :poltergeist do |app|
+  Capybara::Poltergeist::Driver.new(app, {js_errors: false})
+end
```

**Comment by nnunn** [comment]
I will fix that right now!

**Comment by pgwillia** [comment]
./app/assets/stylesheets/era_custom.css.scss:   background-image: url('slide.jpg');

slide.jpg is called but doesn't exist gives ```ActionController::RoutingError: No route matches [GET] "/assets/slide.jpg"```

ideas for fix:
1. add slide.jpg
2. change the css to reflect an image in the group

**Comment by nnunn** [comment]
I will fix that too.

I can't actually reproduce the first error on my dev machine. I think it
must be an issue in the asset pipeline. Is there a way to see what is being
generated in the head of the page?

**Comment by pgwillia** [comment]
The last thing I have failing is Admin functionality missing from front page. Likely a bigger converstation.

Acknowledgement that the user is logged is also missing.
image

image

**Comment by pgwillia** [comment]
I can't reproduce this in my browser either.  All the pieces seem to be
present.

I wonder if it's related to this:
http://stackoverflow.com/questions/25418597/angularjs-canvasjs-how-to-unit-test

**Comment by pgwillia** [comment]
Here's the full trace -- which doesn't seem to have anything to do with
chartContainer. Sorry for the misdirection:

     Failure/Error: sign_in user
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page.
If you don't care about these errors, you can ignore them by setting
js_errors: false in your Poltergeist configuration (see documentation for
details).

       TypeError: 'undefined' is not an object (evaluating
'this._toolBar.style')
       TypeError: 'undefined' is not an object (evaluating
'this._toolBar.style')
           at http://127.0.0.1:42761/assets/application.js:12470
           at http://127.0.0.1:42761/assets/application.js:12474
           at http://127.0.0.1:42761/assets/application.js:12479
           at http://127.0.0.1:42761/assets/application.js:12792
           at http://127.0.0.1:42761/assets/application.js:12401
           at http://127.0.0.1:42761/assets/application.js:3120
           at http://127.0.0.1:42761/assets/application.js:3232
           at http://127.0.0.1:42761/assets/application.js:3444
           at http://127.0.0.1:42761/assets/application.js:3475 in completed
       TypeError: 'null' is not an object (evaluating
'g.innerHTML=h+"</ul>"')
       TypeError: 'null' is not an object (evaluating
'g.innerHTML=h+"</ul>"')
           at http://127.0.0.1:42761/assets/application.js:12868
           at
http://cdn.syndication.twimg.com/widgets/timelines/586195044660424704?&lang=en&callback=twitterFetcher.callback&suppress_response_codes=true&rnd=0.5023724227212369:1

**Comment by nnunn** [comment]
Great - that is super helpful.

thanks

**Comment by nnunn** [comment]
Ok - I've fixed a few of the problems. Unfortunately, there is a javascript issue that I can't track down. It doesn't appear in my dev version. 

Also we will have to talk about whether we want the Admin functionality on the main page.

**Comment by pgwillia** [comment]
Just looking through the OWASP checklist and I noticed that the logout button disappeared from all second level pages. The checklist is especially concerned with restricted pages (dashboard, etc). @nnunn can you fix this?

image
vs 
image


The OWASP item says "v3.5 Verify that all pages that require authentication to access them have logout links."

**Comment by nnunn** [comment]
I just pushed up the changes to fix this logout issue.

**Comment by pgwillia** [comment]
Looks good to me. Now just waiting for travis.

**Pull request merged**
