### PR TITLE
Collection/Community page

### PR DESCRIPTION
**Pull request by criedlberger**

### CODE REVIEW

**Comment by criedlberger** [comment]
@pbinkley I have created a new pull request and branch for the Collection/Community landing page.

**Comment by pbinkley** [comment]
Thanks, I'll check it out after the town hall.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
Closes #962

**Comment by pbinkley** [comment]
There are still four failing specs. I'm not sure whether these should be dealt with here, or in #909 , which also deals with nesting. Should we maybe try merging @mbarnett 's branch into this and see how it works? 

```
$ bundle exec rspec spec/features/collection/collection_spec.rb

...

Finished in 6 minutes 13 seconds (files took 6.22 seconds to load)
24 examples, 4 failures, 2 pending

Failed examples:

rspec ./spec/features/collection/collection_spec.rb:225 # collection show collection as admin should allow me to nest collections
rspec ./spec/features/collection/collection_spec.rb:306 # collection delete items from collection should add and delete item from collection
rspec ./spec/features/collection/collection_spec.rb:337 # collection collection with a member file should not have edit and delete options
rspec ./spec/features/collection/collection_spec.rb:378 # collection create collection should be able to create a collection
```


Peter Binkley, Ph.D., MLIS

**Comment by mbarnett** [comment]
#909 is already a very complicated fix that is taking forever. I think at this point merging it into this is just going to create an even crazier and more intractable mess.

I'd say fix these issues here, and then when #909 is ready I'll worry about reconciling it with the current state of master.

**Comment by pbinkley** [comment]
Specs are passing, but the collection edit form is broken (see screenshot). I was logged in as admin, navigated to a collection, then clicked edit. This works on plano.
edit

**Pull request merged**
