### PR TITLE
modify the dataverse migration script to properly decode html in data…

### LINKED ISSUE #1203: Decoding HTML tags in text fields
Now with the fix to #704 in place, proper html tags can be handled in the text fields. But migrated objects from Thesis Deposit and Dataverse might have the html tags encoded with their html entities (& lt; & gt; & amp; etc.). When rendering the views, these html entities need to be decoded, so that it can be displayed properly as a HTML text.  This can be used for decoding on the view:
https://github.com/ualbertalib/HydraNorth/blob/9eba023736bfb2ea2d73b8fc3f851cbe76a02fcf/lib/tasks/migration.rake#L238

### PR DESCRIPTION
**Pull request by weiweishi**
…verse metadata files, add rake task to clean up withdrawn studies, and remove the obsolete task. Closes #1203

### CODE REVIEW

**Comment by pgwillia** [comment]
1. specs: Finished in 35 minutes 16 seconds (files took 11.28 seconds to load)
436 examples, 1 failure, 5 pending
```
Failures:

  1) Migration rake tasks migration:update_dataverse_fields rights and description fields should have been updated
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: Rake::Task["migration:update_dataverse_fields"].invoke
          RuntimeError:
            Don't know how to build task 'migration:update_dataverse_fields' (see --tasks)
          # ./spec/tasks/dataverse_migration_rake_spec.rb:107:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: Rake::Task["migration:update_dataverse_fields"].reenable
          RuntimeError:
            Don't know how to build task 'migration:update_dataverse_fields' (see --tasks)
          # ./spec/tasks/dataverse_migration_rake_spec.rb:115:in `block (3 levels) in <top (required)>'
```
2. Would be useful to update spec/fixtures/migration/test-metadata/dataverse/ to match the output that @johnhuck is providing.
3. Missing end to bold text markdown in README so that bold text isn't rendered
4. Provide example command in README, i.e. ```rake migration:dataverse_objects['spec/fixtures/migration/test-metadata/dataverse/']```

**Comment by weiweishi** [comment]
@pgwillia ready for another review.

**Comment by pgwillia** [comment]
Just checking that this is the expected formatting:

From the catalog screen
screenshot from 2016-09-16 09-41-41
From the file screen
screenshot from 2016-09-16 09-41-20

**Comment by johnhuck** [comment]
Thanks, @pgwillia. As you probably guessed, the square brackets and quotation marks surrounding the description field content are not expected and the backslashes in front of the quotation marks around the statement 'This project/resource ... Alberta government' look like remnants from escaping the quotation marks, which should be there.

**Comment by johnhuck** [comment]
The uploader has inserted a line break after 'OpenGenetics Lectures', which is not expressed in the native Dataverse display, so that aspect of the formatting is not related to the ERA ingest process.

**Comment by weiweishi** [comment]
It doesn't display the square brackets and additional slash for escaping quotation marks in production:
https://era.library.ualberta.ca/files/fj236214z. Checking into the cause right now.

**Comment by weiweishi** [comment]
@pgwillia fixed the description field. Thanks!

**Pull request merged**
