### PR TITLE
Sufia6.1

### PR DESCRIPTION
**Pull request by criedlberger**

### CODE REVIEW

**Comment by pbinkley** [comment]
It looks like Gemfile.lock hasn't been updated (it still shows Sufia 6.1, while Gemfile has 6.2). I've tried deleting it and doing ```bundle update```: all the tests pass and everything looks good. Given my recent record though I'm wary about committing a change that turns out to break on other people's environments. @criedlberger , do you want to try update Gemfile.lock and make sure it's ok?

**Comment by pgwillia** [comment]
I am also seeing passing tests and successful migrations, but am having trouble using the webapp.

I've committed a couple things I thought were missing. 

Saw this but didn't fix it:
image

Also struggled with
* apache/passenger
* db migration

**Comment by pbinkley** [comment]
I've rebased on master.

**Comment by pgwillia** [comment]
I'm working through this too. I'm applying the playbook from scratch with this branch. So far I've resolved the db:migrate issues and created a vagrant box that works with VirtualBox 5.0 and Vagrant 1.7.4.

**Comment by pgwillia** [comment]
Resque worker fails for embargo:

hydranorthdev.library.ualberta.ca:965 on BATCH_UPDATE at 10 minutes ago
Class
 Sufia::Resque::MarshaledJob
Invalid visibility: "embargo"

**Comment by weiweishi** [comment]
This means the visibility doesn't get interpreted correctly in here:
https://github.com/ualbertalib/HydraNorth/blob/master/app/actors/hydranorth/manages_embargoes_actor.rb

Method interpret_embargo_visibility should translate embargo to valid
visibility attributes.
This file is not available in sufia4.2 branch?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pgwillia** [comment]
Peter, would you mind if I clean up the history and merge this PR?  I'll then open two new issues for the formatting and embargo bugs.

Wait.  I see that I'm not assigned to this.  Sorry. It's all yours.

**Comment by pbinkley** [comment]
Yeah, sorry, we got jumbled up. I'm still working through some problems
with data import in my environment, but they may be (probably are) local.
As far as you're concerned this is ready to merge?

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pgwillia** [comment]
I would squash the 7 upgrade commits into one and properly rebase rather than having a merge commit.  It looks like you've added two other commits "Fix my misfixed ualterms namespace" and "Dataverse migration works" which seem irrelevant to the PR/issue, but I'm probably missing something.

**Comment by pbinkley** [comment]
Yes, I was going to squash before merging. The "misfixed ualterms" was
another PR, and came in when I rebased on master; I'm not sure why it ended
up on its own when other recent commits to master didn't. I'll omit it. The
"Dataverse migration" one is necessary for Sufia 6.2 (to make it use the
Noid minter, and to make the test work).

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pgwillia** [comment]
It looks like that same change is in the "final revision" commit.

**Comment by pgwillia** [comment]
"[DEPRECATION] `CollectionsController` will be fixed in Sufia 6.0.1 and can be removed from HydraNorth

**Comment by pbinkley** [comment]
We won't merge this until we have tagged a release for Sonya's user tests, so as not to complicate the deployment with all of the upgraded gems (including Rails).

**Comment by pbinkley** [comment]
The working code is now in branch sufia6.1-squash - we will create a new PR from there to merge instead of this one.

**Pull request closed without merging**
