### PR TITLE
Temporarily redirect to /dashboard/files to avoid slowness on /dashboard

### PR DESCRIPTION
**Pull request by mbarnett**

### CODE REVIEW

**Comment by pgwillia** [comment]
This fix will apply to all users, not just admins... is that the intention?

**Comment by pgwillia** [comment]
Confirmed that you got 'em all!

```
[root@hydranorthdev hydranorth]# grep dashboard_index_path -R `bundle show sufia` | grep redirect_to
/usr/lib64/ruby/gems/2.3.0/gems/sufia-6.2.0/app/controllers/concerns/sufia/batch_edits_controller_behavior.rb:        redirect_to sufia.dashboard_index_path
[root@hydranorthdev hydranorth]# grep dashboard_index_path -R . | grep redirect_to
[root@hydranorthdev hydranorth]#
```

**Comment by mbarnett** [comment]
It looks to me like there's some kind of issue where ccid users are hitting the dashboard on login even after changing the admin branch in that one path, so it seemed easier to cover all our bases for the time being (and theoretically if users start transfer between each other for some reason, this would impact them too anyways).

**Comment by pgwillia** [comment]
Failing tests.  Should be easy to fix.
```
Failures:

  1) download link where item has doi identifier should be DOI in action
     Failure/Error: visit "dashboard/files"
     ActionController::RoutingError:
       No route matches [GET] "/dashboard/dashboard/files"
     # ./spec/features/doi_spec.rb:37:in `block (3 levels) in <top (required)>'

  2) download link where item has no identifier should be download in action
     Failure/Error: visit "dashboard/files"
     ActionController::RoutingError:
       No route matches [GET] "/dashboard/dashboard/files"
     # ./spec/features/doi_spec.rb:67:in `block (3 levels) in <top (required)>'

  3) SAML Users with no existing account should be able to use SAML to create acount
     Failure/Error: expect(current_path).to eq('/dashboard')
       
       expected: "/dashboard"
            got: "/dashboard/files"
       
       (compared using ==)
     # ./spec/features/saml_spec.rb:27:in `block (3 levels) in <top (required)>'

  4) SAML Users with confirmed CCID accounts should not be prompted to link account
     Failure/Error: expect(current_path).to eq('/dashboard')
       
       expected: "/dashboard"
            got: "/dashboard/files"
       
       (compared using ==)
     # ./spec/features/saml_spec.rb:144:in `block (3 levels) in <top (required)>'
```

**Comment by mbarnett** [comment]
Fixed the DOI specs to properly use a non-relative path, and marked the SAML tests as pending since this behaviour should be fixes as soon as a full fix for #1233 is in place

**Pull request merged**
