### PR TITLE
Update for Sufia 6.0.0.rc1 and Fedora 4

### PR DESCRIPTION
**Pull request by pgwillia**

### CODE REVIEW

**Comment by weiweishi** [comment]
See this problem when trying to run the playbook from the head of Default or HydraNorth.fedora4 branch in code repo. Wondering if any of you have seen it?

 TASK: [passenger | install passenger_mod] *************************************
==> hydranorth: failed: [192.168.33.17] => {"cmd": "pass******** --auto --languages ruby", "failed": true, "rc": 2}
==> hydranorth:
==> hydranorth: msg: [Errno 2] No such file or directory

**Comment by weiweishi** [comment]
Problem and Solution:

if you see a "command not found" error, find the passenger Gem and include the path in your command /usr/local/lib/ruby/gems/2.0.0/gems/passenger-4.0.37/bin/passenger-install-apache2-module. Parts of this path may be different depending on the configuration of your system.

**Comment by weiweishi** [comment]
More problem with the playbook:
TASK: [hydranorth | Install bundler -- only thing really useful about ual-rails] ***
failed: [192.168.33.17] => {"cmd": "/usr/bin/gem install --version 1.7.12 --no-user-install --no-rdoc --no-ri bundler", "failed": true, "rc": 1}
stderr: ERROR:  Error installing bundler:
        "bundle" from bundler conflicts with /usr/bin/bundle

msg: ERROR:  Error installing bundler:
        "bundle" from bundler conflicts with /usr/bin/bundle


I think the two issues are related - something about the system directory for gems.

**Comment by pgwillia** [comment]
These things are starting to sound like you have an old version of the
Vagrant box. What do you see when you list the vagrant boxes installed?
This is what I see

```
vagrant box list
...
ual/hydranorth      (virtualbox, 2.0.0)
```

From Vagrant documentation
<https://docs.vagrantup.com/v2/boxes/versioning.html>
vagrant box list only shows *installed* versions of boxes.
You can check if the box you're using is outdated with vagrant box outdated.
Finally, you can update boxes with vagrant box update.

When vagrant box update isn't successful I ```vagrant box remove
ual/hydranorth```

**Pull request merged**
