### PR TITLE
Nested collections fixes #75

### LINKED ISSUE #75: ERA_Collections: Nested collections
As admin I want to be able to create nested collections so that I can maintain a logical structure of broadly-focused collections with more sharply focused sub-collections
- [x] have link-to-parent and link-to-child metadata elements to enable up and down navigation
- [x] display links
- [ ] distinguish community and collection with a flag, so that the navigation can imitate current ERA with browsing of communities first, then links down to collection
- [ ] stretch goal: enable faceting by collection of collection, so as to allow searching across all nested collections

### PR DESCRIPTION
**Pull request by pgwillia**
* add requirements to collection model
  * cannot collect self
  * index collection it belongs to
* given a nested collection make sure you can view it
* add collections to collection in UI
 * side effect is giving 'files shared with me' batch options
* capybara feature test

### CODE REVIEW

**Comment by pbinkley** [comment]
It's letting me insert a collection to a child collection, and end up with Collection 3 includes Collection 2 and Collection 2 includes Collection3
collectionloop

**Comment by pgwillia** [comment]
Isn't that the expected behaviour?

**Comment by pbinkley** [comment]
I thought you fixed it to prevent loops - but no, I'm mixed up, that was just to prevent self-inclusion. Sorry about that.

**Comment by pbinkley** [comment]
But: a UX problem: when you click "Add Collection", you get a menu of collections to add to the current one, but you don't have an indication of the current one now. It's easy to lose focus at the point and forget what the parent collection was. (And it will get worse when we have all the ERA collections in that list). Could we add a green-shaded message to the selections screen, like "Select collection to add to Collection X"?

**Comment by pbinkley** [comment]
Decided to defer consideration of the usability issue until its priority is clear, given that this will be used mostly by admin if at all.

**Pull request merged**
