### PR TITLE
fixes CCID for local Rails dev environment

### PR DESCRIPTION
**Pull request by mbarnett**
We broke this when setting up the real mappings for production with IST.

Like it says on the tin, this fixes it when Rails is run in development mode locally

### CODE REVIEW

**Comment by pgwillia** [comment]
Implies that plano either a) isn't actually environment=development or b) won't have ualberta shib configured in the future.

**Comment by mbarnett** [comment]
Since Plano and the Vagrants are configured differently, it might be an argument that they shouldn't be sharing a Rails environment?

**Comment by mbarnett** [comment]
(this might also be an argument for running Plano in a different (non-development) Rails environment: https://github.com/ualbertalib/HydraNorth/issues/685. It won't correctly model some kinds of behaviour, like viewpath lookup, that we'll see in Production, because of Rails being annoying like that)

**Comment by mbarnett** [comment]
I've got a better solution for this incoming on another branch

**Pull request closed without merging**
