### PR TITLE
spec the callback for Google OAuth resolves #193

### LINKED ISSUE #193: Enable Dropbox/Drive deposit
Investigate how much work it would be to turn this on - may need new Google account for Admin to manage the ownership (use the one we use for Google Analytics?)
This would be a nice feature to turn on, as an example of new functionality beyond current ERA.

### PR DESCRIPTION
**Pull request by pgwillia**

### CODE REVIEW

**Comment by weiweishi** [comment]
Had the following tests failed:
  
1) My::AllController Admin should respond with success
     Failure/Error: get :index, use_route: :dashboard
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"my/all"}
     # ./spec/controllers/my/all_controller_spec.rb:63:in `block (3 levels) in <top (required)>'
  2) My::AllController Admin shows the correct files
     Failure/Error: get :index, use_route: :dashboard
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"my/all"}
     # ./spec/controllers/my/all_controller_spec.rb:68:in `block (3 levels) in <top (required)>'
  3) My::FilesController Logged in user should respond with success
     Failure/Error: get :index
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"my/files"}
     # ./spec/controllers/my/files_controller_spec.rb:28:in `block (3 levels) in <top (required)>'
  4) My::FilesController Logged in user shows the correct documents
     Failure/Error: get :index
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"my/files"}
     # ./spec/controllers/my/files_controller_spec.rb:33:in `block (3 levels) in <top (required)>'
  5) UsersController#index requesting html should test users
     Failure/Error: get :index
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"users"}
     # ./spec/controllers/users_controller_spec.rb:19:in `block (4 levels) in <top (required)>'
  6) UsersController#index requesting json should display users
     Failure/Error: get :index, format: :json
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"users", :format=>:json}
     # ./spec/controllers/users_controller_spec.rb:27:in `block (4 levels) in <top (required)>'
  7) UsersController#index query users does not find the expected user via email
     Failure/Error: get :index,  uq: @u1.email
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"users", :uq=>"admin@example.com"}
     # ./spec/controllers/users_controller_spec.rb:36:in `block (4 levels) in <top (required)>'
  8) UsersController#index query users finds the expected user via email
     Failure/Error: get :index,  uq: @u2.email
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"users", :uq=>"jilluser@example.com"}
     # ./spec/controllers/users_controller_spec.rb:41:in `block (4 levels) in <top (required)>'
  9) UsersController#index query users finds the expected user via display name
     Failure/Error: get :index,  uq: "User"
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"users", :uq=>"User"}
     # ./spec/controllers/users_controller_spec.rb:51:in `block (4 levels) in <top (required)>'
  10) UsersController#index query users uses the base query
     Failure/Error: get :index
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"users"}
     # ./spec/controllers/users_controller_spec.rb:62:in `block (4 levels) in <top (required)>'
  11) UsersController admin #lock_access
     Failure/Error: get :lock_access, id: user.user_key, use_route: :users
     ActionController::UrlGenerationError:
       No route matches {:action=>"lock_access", :controller=>"users", :id=>"user12@example.com"}
     # ./spec/controllers/users_spec.rb:30:in `block (3 levels) in <top (required)>'
  12) UsersController admin #unlock_access
     Failure/Error: get :unlock_access, id: locked_user.user_key, use_route: :users
     ActionController::UrlGenerationError:
       No route matches {:action=>"unlock_access", :controller=>"users", :id=>"user13@example.com"}
     # ./spec/controllers/users_spec.rb:36:in `block (3 levels) in <top (required)>'
  13) UsersController admin #edit when admin attempts to edit another profile no redirect to show profile
     Failure/Error: get :edit, id: user.user_key
     ActionController::UrlGenerationError:
       No route matches {:action=>"edit", :controller=>"users", :id=>"user14@example.com"}
     # ./spec/controllers/users_spec.rb:20:in `block (5 levels) in <top (required)>'
  14) UsersController not admin #lock_access
     Failure/Error: get :lock_access, id: user.user_key, use_route: :users
     ActionController::UrlGenerationError:
       No route matches {:action=>"lock_access", :controller=>"users", :id=>"user15@example.com"}
     # ./spec/controllers/users_spec.rb:48:in `block (3 levels) in <top (required)>'
  15) UsersController not admin #unlock_access
     Failure/Error: get :unlock_access, id: locked_user.user_key, use_route: :users
     ActionController::UrlGenerationError:
       No route matches {:action=>"unlock_access", :controller=>"users", :id=>"user17@example.com"}
     # ./spec/controllers/users_spec.rb:54:in `block (3 levels) in <top (required)>'

**Comment by pgwillia** [comment]
Yeah, I saw that yesterday.  Need to add a second engine's routes to spec_helper.rb which I'm still working out how to do.

**Comment by weiweishi** [comment]
It seems this is ready to be merged?

**Comment by pgwillia** [comment]
I'm not completely convinced this test is doing what I want it to do but all tests are passing now.

I think this test is checking that the BrowseEverything controller has the route needed, not necessarily that HydraNorth has that route mounted at the specific target in HydraNorth.

**Pull request merged**
