### PR TITLE
674 951 dataverse ingest

### LINKED ISSUE #674: Author Order between Dataverse and HydraNorth
This appears to be an issue again in the latest import after being apparently resolved in a previous issue.

https://github.com/ualbertalib/HydraNorth/issues/555

Current example:
https://hydranorth.library.ualberta.ca/files/f4752g834#.VhL_NSpViko

Incidentally, if the same remedy can be applied to Subject order that might not be a bad thing.

### PR DESCRIPTION
**Pull request by weiweishi**
fixes #674, #951, and ready for #981

### CODE REVIEW

**Comment by pbinkley** [comment]
I'm getting one failed spec:

```
  1) Migration rake tasks migration:dataverse_objects should update the metadata and not created new record
     Failure/Error: id = doc["id"]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/tasks/dataverse_migration_rake_spec.rb:79:in `block (3 levels) in <top (required)>'
```

Looking into it now.

**Comment by pbinkley** [comment]
Further: I tried ingesting the test Dataverse object with: 
```
bundle exec rake migration:dataverse_objects['spec/fixtures/migration/test-metadata/dataverse']
```
Then I modified that record (I added another author) and ingested it again with the same command. It produced a new object with a new noid.

I'm looking into why ```duplicated?``` failed to find the first object. If I replicate the Solr query in the web interface, it finds both now.

**Comment by weiweishi** [comment]
@pbinkley pushed a fix to the bug you identified.

**Comment by pbinkley** [comment]
The new problem was [here](https://github.com/ualbertalib/HydraNorth/pull/1043/files#diff-b8835142c0b1c24a9a4fe38907c719faR238): my failed attempts had created 3 records with the same DOI, so the ```== 1``` was failing. I suppose we should log an error if there is more than one. I've deleted the extras and now I'm getting a different error, which I'll look into tomorrow.

**Comment by weiweishi** [comment]
@pbinkley pushed a new PR to catch the error message you identified above, as well as the issue of adding to community member_ids (we no longer use member_ids as the information is captured in object's solr record.)

**Comment by pbinkley** [comment]
I've added an explicit test to ensure that the duplicate didn't create a new record. I had to add [this](https://github.com/ualbertalib/HydraNorth/pull/1043/files#diff-d9a8b33daf55e89fa64cbdbd3de0290fR19) at the beginning of the spec to make sure that broken records from previous runs don't look like duplicates of the imported record. Since @wshi is away, and this is a small change limited to the spec, I'll go ahead and merge as is.

**Pull request merged**
