### PR TITLE
removing total_items improves performance for large collections fixes…

### PR DESCRIPTION
**Pull request by pgwillia**
… #692

exclude long running test using: rspec --tag ~slow spec
only long running test using: rspec --tag slow spec

### CODE REVIEW

**Comment by pbinkley** [comment]
@pgwillia  I'm getting one failed test:
```
  1) CollectionsController index performance should be fast
     Failure/Error: expect( Benchmark.realtime{
       expected: < 0.5
            got:   3.30547144
```
Are you getting < 0.5 on your local vm, or can I ascribe this to the environment and merge?

**Comment by pgwillia** [comment]
I was getting the expected performance on my VM (with 4 GB memory). 0.5 to 3.3 is a big difference there might be cause for concern there.

**Comment by mbarnett** [comment]
Depending on what else the machine is running, what swap pressure is like, etc, I could see a 6x swing in performance pretty easily. A simple git stat on my vagrant can take anywhere from < 1 second to upwards of 30 depending on how warm everything is.

We may need to think up a better way of testing that performance, long term.

**Comment by pbinkley** [comment]
Hmm, I'm using 2GB, which would probably explain it. I'll try again with 4GB.

**Comment by pbinkley** [comment]
Oh, wait, no, it was 4GB.  I'm inclined to merge on the grounds that 3.3 is better than the error we were getting before. We can determine whether more work is needed when we see it on production hardware.

**Pull request merged**
