### PR TITLE
New Generic File upload form

### PR DESCRIPTION
**Pull request by weiweishi**
#129 as part A of #30. 

Note the instruction of running selenium tests is in the note for #129

### CODE REVIEW

**Comment by pbinkley** [comment]
I'm getting this error - does it look familiar? I haven't finished investigating.
screenshot from 2015-03-24 18 29 07

**Comment by weiweishi** [comment]
This should not happen if the resque job finishes.  I will look into why it
will happen when resque still processing

Weiwei

I'm getting this error - does it look familiar? I haven't finished
investigating.
[image: screenshot from 2015-03-24 18 29 07]
<https://cloud.githubusercontent.com/assets/272816/6816084/00e0b35e-d254-11e4-8bda-e216adbb93b6.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/pull/143#issuecomment-85758319>.

**Comment by pbinkley** [comment]
It looks like I had everything up to date on the external instance of HydraNorth, but I needed to run bundle install in the VM. I'm retesting now.

**Comment by pbinkley** [comment]
Nope, still getting same error.

**Comment by weiweishi** [comment]
Confirmed the error message only occurs if resque has not finished the
processing job.
Have changed the code to make sure it doesn't happen.
Will refactor my testing code so it's not entirely depending on the resque
job to finish. However some verification of the information will still need
to depend on it. Do you see the files ever get processed in your Hydranorth
instance?

**Comment by weiweishi** [comment]
Confirmed the error message was caused by resque not completing the batch upload job. Modify the code to handle it correctly. Could you please check if Resque is running properly on your VM? I've updated the test and please give it another try.

**Comment by pgwillia** [comment]
I think these changes may have unintended consequences on Collections.

**Comment by weiweishi** [comment]
I'm updated the spec test as part of pull request #163

**Comment by weiweishi** [comment]
Something we should take a closer look as well.

Weiwei

Begin forwarded message:

*From:* Andrew Woods <awoods@duraspace.org>
*Date:* April 20, 2015 at 8:08:58 AM MDT
*To:* Hydra-Tech <hydra-tech@googlegroups.com>
*Cc:* "islandora@googlegroups.com" <islandora@googlegroups.com>,
islandora-dev@googlegroups.com,  "fedora-tech@googlegroups.com" <
fedora-tech@googlegroups.com>
*Subject:* *Re: [hydra-tech] auditTrail migration fcrepo3 -> fcrepo4*
*Reply-To:* hydra-tech@googlegroups.com

Hello Nick,
This is a very important aspect of Fedora 3 to 4 migrations. Thank you for
motivating consistency across the community. Given the recent Fedora 4
"Audit Service" work, new and migrated audit events will now finally be
searchable in a meaningful way. Since these events will be available as
linked data, consistency of mapping from the outset will enrich the
opportunities for common tooling and semantic clarity.

All,
Please review and provide feedback on the audit event mappings proposed by
Nick!

Regards,
Andrew

On Mon, Apr 20, 2015 at 9:28 AM, Nick Ruest <ruestn@gmail.com> wrote:

> Hi folks-
>
> As part of the Islandora and Fedora Integration Project, we are working on
> mapping our auditTrail from fcrepo3 to fcrepo 4.
>
> We've pulled together what we think is a list of the standard auditTrail
> events in fcrepo3 and mapped them to the fcrepo4 audit service[1]. I'd love
> to get feedback on this to make sure we've identified everything, and our
> mappings are sane. Moreover, I think it would be great if we could have a
> general consensus around the mappings, and use them across our communities
> for our migrations.
>
> cheers!
>
> -nruest
>
> [1]
> https://github.com/Islandora-Labs/islandora/blob/7.x-2.x/docs/technical-documentation/migration.md#audit-log-migration
>
> --
> You received this message because you are subscribed to the Google Groups
> "Hydra-Tech" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to hydra-tech+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>

 --
You received this message because you are subscribed to the Google Groups
"Hydra-Tech" group.
To unsubscribe from this group and stop receiving emails from it, send an
email to hydra-tech+unsubscribe@googlegroups.com.
For more options, visit https://groups.google.com/d/optout.

**Pull request merged**
