### PR TITLE
1056 add some resourcesync elements

### PR DESCRIPTION
**Pull request by pgwillia**
* expect performance will be slower because it can no longer be a Solr only operation; Fedora is required for medatadata
* ```rake sitemap:generate``` should result in public/sitemap.xml with
```  
  <url>
    <loc>http://era.library.ualberta.ca/files/w6634361c</loc>
    <lastmod>2016-05-06T20:20:35Z</lastmod>
    <priority>1</priority>
    <changefreq>weekly</changefreq>
    <rs:md hash="urn:sha1:391d36d6aef29ea2ed2cb1184b63a8c609d8b434" length="379260" type="image/jpeg"/>
  </url>
```

### CODE REVIEW

**Comment by pgwillia** [comment]
Reviewing this for myself I got to wondering if that was an appropriate use of rs:md hash.  The hash is actually for http://era.library.ualberta.ca/downloads/w6634361c.  We can use the ```<rs:ln href="/downloads/w6634361c" rel="content"/>``` tag to make this relationship more explicit. That said, should the sitemap //url/loc be the metadata or the datastream?

**Comment by pgwillia** [comment]
That's better.  Now the output should read something like
```
  <url>
    <loc>http://era.library.ualberta.ca/files/w6634361c</loc>
    <lastmod>2016-05-06T20:20:35Z</lastmod>
    <priority>1</priority>
    <changefreq>weekly</changefreq>
    <rs:md type="text/html"/>
    <rs:ln href="/downloads/w6634361c" rel="content" hash="urn:sha1:391d36d6aef29ea2ed2cb1184b63a8c609d8b434" length="379260" type="image/jpeg"/>
  </url>
```

**Comment by pgwillia** [comment]
Modified tests so that the expected results aren't dependent on the current date. @pbinkley should have passing tests now.

**Comment by pbinkley** [comment]
If I test this with ```rspec spec/controllers/recent_controller_spec.rb``` in the Sprint41 branch, which has several recent PRs merged, I get three failed specs. Apologies if it's my merge that messed things up.

```
Failures:

  1) RecentController GET #index includes date buckets for crawling
     Failure/Error: expect(assigns(:date_buckets)).to include "2016"=>[["2016-04-01T00:00:00Z", 1]]
       expected {"2016" => [["2016-05-01T00:00:00Z", 1]]} to include {"2016" => [["2016-04-01T00:00:00Z", 1]]}
       Diff:
       @@ -1,2 +1,2 @@
       -[{"2016"=>[["2016-04-01T00:00:00Z", 1]]}]
       +"2016" => [["2016-05-01T00:00:00Z", 1]],
     # ./spec/controllers/recent_controller_spec.rb:36:in `block (3 levels) in <top (required)>'

  2) RecentController GET #index with a document not created in the last two weeks includes date buckets for crawling
     Failure/Error: expect(assigns(:date_buckets)).to include "2016" => [["2016-03-01T00:00:00Z", 1], ["2016-04-01T00:00:00Z", 2]]
       expected {"2016" => [["2016-04-01T00:00:00Z", 1], ["2016-05-01T00:00:00Z", 2]]} to include {"2016" => [["2016-03-01T00:00:00Z", 1], ["2016-04-01T00:00:00Z", 2]]}
       Diff:
       @@ -1,2 +1,2 @@
       -[{"2016"=>[["2016-03-01T00:00:00Z", 1], ["2016-04-01T00:00:00Z", 2]]}]
       +"2016" => [["2016-04-01T00:00:00Z", 1], ["2016-05-01T00:00:00Z", 2]],
     # ./spec/controllers/recent_controller_spec.rb:111:in `block (4 levels) in <top (required)>'

  3) RecentController GET #index with a document not created in the last year includes date buckets for crawling
     Failure/Error: expect(assigns(:date_buckets)).to include "2016"=>[["2016-04-01T00:00:00Z", 1]]
       expected {"2015" => [["2015-05-01T00:00:00Z", 1]], "2016" => [["2016-05-01T00:00:00Z", 1]]} to include {"2016" => [["2016-04-01T00:00:00Z", 1]]}
       Diff:
       @@ -1,2 +1,3 @@
       -[{"2016"=>[["2016-04-01T00:00:00Z", 1]]}]
       +"2015" => [["2015-05-01T00:00:00Z", 1]],
       +"2016" => [["2016-05-01T00:00:00Z", 1]],
     # ./spec/controllers/recent_controller_spec.rb:131:in `block (4 levels) in <top (required)>'
```

**Comment by pgwillia** [comment]
I had rebased on Sprint41. You'll see those commits in my branch. I'll take
a look tomorrow.

**Comment by pbinkley** [comment]
Just to confuse myself more, I found there are two
branches: 1056_add_some_resourcesync_element
and 1056_add_some_resourcesync_elements . They seem to have the same
commits, but with different hashes. And neither of them was in my merge.
Merging now.






Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
All good.

**Pull request merged**
