### PR TITLE
Use correct presenter class on single use file links. Closes #798.

### LINKED ISSUE #798: single use link to file not working?
on my list of files, clicked on single use link to file. on one click it doesn't seem to do anything but if ai click it again it gives me the link and says it's been copied to my clipboard. click ok but when i paste the link into a browser window i get an error:

e.g., https://era.library.ualberta.ca/single_use_link/show/58be80dc24300db5fb226fba473f9d865df00211c4ecefbd9a0892d157120594

screen shot 2015-10-19 at 3 21 56 pm

i confess to not having tried this function previously

### PR DESCRIPTION
**Pull request by mbarnett**

### CODE REVIEW

**Comment by pbinkley** [comment]
The link itself still doesn't work for me, either on my dev vm or on plano (I've deployed this branch). Does it work in your environment? I'm generating on Firefox and then trying the link on Chrome. I get "Single Use Link Expired or Not Found" every time.

**Comment by mbarnett** [comment]
It was working for me. I'll take a look on Plano

**Comment by mbarnett** [comment]
Seems to be working for me on Plano? Generated a few different links to files with different visibilities, all worked going from generating link in Firefox in VM to visiting link in Chrome on Windows

**Comment by pbinkley** [comment]
Ok - I've tried going the other way (create on Chrome, test on Firefox),
and it worked. I wonder if it's something weird about flash on linux that's
causing my problems. I'll merge, and I'll be interested to see if it works
for me in production.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Pull request merged**
