### PR TITLE
add a new graduation date to the list 

### PR DESCRIPTION
**Pull request by weiweishi**
address #1319

### CODE REVIEW

**Comment by murny** [comment]
Looks good :shipit:!

I will say for HydraNorth2 most of this configuration should be in a MySQL DB as a table and be CRUD-able in the admin UI so Leah or someone else can fix this themselves? Because this looks like a recurring bug/fix that will happen twice every year. For example around 2017-06 Leah is going to make the exact same request. Which isn't reasonable. Maybe this should be an raised as an issue in the hydranorth2 admin gem?

**Comment by weiweishi** [comment]
:+1: on storing the values in DB instead of in the configuration file, many other configuration values in sufia.yml should be set up that way. And :+1:  on including this in the admin UI

**Comment by pgwillia** [comment]
@weiweishi what conditions have to exist to see this value in a drop down?

**Comment by weiweishi** [comment]
Only displays when Admin edit an thesis object. @pgwillia

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Pull request merged**
