### PR TITLE
Migration fixes

### LINKED ISSUE #251: ERA Migration - Special reports
We will migrate CS technical reports and Structural Engineering reports. It needs small changes to the migration script to handle the special ids.

### LINKED ISSUE #267: Date_modified should be the original modified date
date_modified should be the actual last modified date of the object, not the date migrated.

### LINKED ISSUE #271: Date_uploaded doesn't display on the search result page.

### LINKED ISSUE #274: Limit your search (by) collection facet on search results page lists collection NOIDs rather than titles

### PR DESCRIPTION
**Pull request by weiweishi**
Changes include:
* Changed date_modified to last modified time of the object instead of the migration time fixes #267 
* Handles the date fields correctly by converting them from string to DateTime fixes #271
* Add collection title to hasCollection in GenericFile fixes #274 
* Handle multiple creators/contributors correctly
* Only active/non-deleted objects (filename starting with uuid_)from ERA will be seleted and migrated. also updated README.md
* Improved logging messages	4a5e33c
* Remove newline and tab from Generic File's description text
* Handle special reports and modify seed collections to avoid conflicts in migration fixes #251 
 * Updated the test-metadata with the latest metadata transformation (soft launch 2015-05-14)

### CODE REVIEW

**Comment by pgwillia** [comment]
Is the documentation broken by this change? None of the suggested invocations work:
```
[root@hydranorthdev hydranorth]# migration:user_migration['lib/tasks/migration/test-metadata/collection/']rake migration:era_collection_community['lib/tasks/migration/test-metadata/collection']
bash: migration:user_migration[lib/tasks/migration/test-metadata/collection/]rake: No such file or directory
[root@hydranorthdev hydranorth]# rake migration:eraitem['lib/tasks/migration/test-metadata/metadata']
[root@hydranorthdev hydranorth]# cat log/migration.log
# Logfile created on 2015-05-20 14:19:49 -0600 by logger.rb/1.2.8
[INFO  2015-05-20 14:19:49] **************START: Migrate ERA objects *******************
[FATAL 2015-05-20 14:19:49] Invalid directory lib/tasks/migration/test-metadata/metadata
[INFO  2015-05-20 14:19:49] **************FINISH: Migrate ERA objects *******************
```

None of the test metadata was migrated.

**Comment by weiweishi** [comment]
Modified the README.md to reflect the latest change.

**Comment by weiweishi** [comment]
Updated the test-metadata set and README.md for clarification.

**Comment by pgwillia** [comment]
Is 'lib/tasks/migration/test-metadata/users.txt' missing from the PR?

**Comment by pgwillia** [comment]
adding: uuid:846f544d-94db-41b4-9f4a-654e1457ed8c/8-1A_-_Aquatic_Report_for_the_Athabasca__Steepbank_and_Muskeg_Rivers-Appendices.pdf
zip I/O error: No space left on device
zip error: Output file write failure (write error on zip file)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  237k    0  237k    0     0  40127      0 --:--:--  0:00:06 --:--:--  713k
Retrieve metadata used 536.972406284
FAILED: Item uuid:846f544d-94db-41b4-9f4a-654e1457ed8c migration!
No such file or directory @ rb_sysopen - lib/tasks/migration/tmp/uuid:846f544d-94db-41b4-9f4a-654e1457ed8c.zip
["/var/www/sites/hydranorth/lib/tasks/migration.rake:382:in `initialize'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:382:in `open'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:382:in `block in migrate_object'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:201:in `glob'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:201:in `migrate_object'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:99:in `block (2 levels) in <top (required)>'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'", "/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'", "/usr/bin/rake:33:in `<main>'"]

**Comment by weiweishi** [comment]
It's failed because the disk space is too small to create the zip file for
the multi-file objects. This is a small one as all files are PDF. Many
other multi-file objects are video files.  Maybe try to run the tests on
Plano, and I will see if I can find a smaller object.

**Pull request merged**
