### PR TITLE
Include collection ids filter

### PR DESCRIPTION
**Pull request by pbinkley**
I've reviewed Weiwei's and Matt's code and I'd like to get this into today's release. I'll file an issue for the _ssim fields which we can include in tomorrow's release.

### CODE REVIEW

**Comment by pbinkley** [comment]
This is intended to fix #729. I won't close that issue until we see this in operation against the full data set in hydranorth.

**Comment by pgwillia** [comment]
Methinks this was premature. Shall we revert?

**Comment by pbinkley** [comment]
We're deploying a new release tomorrow anyway, and this isn't blocking us
from evaluating anything else in production (is it?), so I say let it wait
for the new release while we file a PR to finish the fix.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
This was superceded by #777

**Pull request merged**
