### PR TITLE
Ccid ui

### PR DESCRIPTION
**Pull request by nnunn**

### CODE REVIEW

**Comment by pgwillia** [comment]
@nnunn is this ready to merge? The last commit says starting...

**Comment by nnunn** [comment]
yes sorry - I shouldn't have used started! It is ready to go

**Comment by mbarnett** [comment]
21 broken tests on this branch (minus 3 that appear to be the usual migration issues). Digging into it.

**Comment by mbarnett** [comment]
Full list if anyone has the cycles to try to sort through this all:

rspec ./spec/features/coauthor_spec.rb:32 # coauthor abby shares work @ included
rspec ./spec/features/coauthor_spec.rb:36 # coauthor abby shares work @ not included
rspec ./spec/features/coauthor_spec.rb:40 # coauthor abby shares work but not a user
rspec ./spec/features/coauthor_spec.rb:48 # coauthor abby shares work barbara can edit and feature
rspec ./spec/features/collection/collection_spec.rb:88 # collection show collection as admin should show a theses collection
rspec ./spec/features/collection/collection_spec.rb:93 # collection show collection as admin should allow me to nest collections
rspec ./spec/features/collection/collection_spec.rb:174 # collection delete items from collection should add and delete item from collection
rspec ./spec/features/my/all_spec.rb:67 # allfiles Admin with user filter Admin can only see user files
rspec ./spec/features/saml_spec.rb:23 # SAML Users with no existing account should be able to use SAML to create acount
rspec ./spec/features/saml_spec.rb:30 # SAML Users with no existing account should be redirected to their protected target after creating an account
rspec ./spec/features/saml_spec.rb:50 # SAML Users with existing legacy accounts whose CCID and legacy address are identical should automatically be associated with their CCID when logging in using it
rspec ./spec/features/saml_spec.rb:65 # SAML Users with existing legacy accounts logging in via SAML for the first time should receive an email confirmation to link to their existing account
rspec ./spec/features/saml_spec.rb:91 # SAML Users with existing legacy accounts logging in via SAML for the first time should not be able to step out of the linking workflow
rspec ./spec/features/saml_spec.rb:100 # SAML Users with existing legacy accounts logging in via SAML for the first time should not be able to enumerate user accounts via the linking workflow
rspec ./spec/features/saml_spec.rb:139 # SAML Users with confirmed CCID accounts should not be prompted to link account
rspec ./spec/forms/generic_file_new_form_spec.rb:13 # generic file new unfold agreement div should find item by publisher
rspec ./spec/forms/generic_file_new_form_spec.rb:30 # generic file new request CSTR item should have CSTR field
rspec ./spec/forms/generic_file_new_form_spec.rb:46 # generic file new check form fields Title and creator is blank
rspec ./spec/tasks/dataverse_migration_rake_spec.rb:27 # Migration rake tasks migration:dataverse dataverse item should be migrated
rspec ./spec/tasks/migration_rake_spec.rb:115 # Migration rake tasks migration:era_collection_community - community Community should be migrated
rspec ./spec/tasks/migration_rake_spec.rb:130 # Migration rake tasks migration:era_collection_community - collection Community should be migrated

**Comment by pbinkley** [comment]
I can look at this.

**Comment by mbarnett** [comment]
I'm currently working on the coauthor spec

**Comment by mbarnett** [comment]
@nnunn seeing a styling issue on dropdowns in the shared permissions area

capture

**Comment by pbinkley** [comment]
Ok - hopefully they all have a common root cause - I'll hold off until you
see what's going on with the coauthors.

**Comment by mbarnett** [comment]
@pbinkley actually it looks like 90% of these will be fixed with one change so we might just end up stepping on each other's toes here. I think I've got this.

**Comment by pbinkley** [comment]
OK, great!

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by mbarnett** [comment]
Tests are now fixed. I'm of the opinion this can be merged if we're ok with that one styling issue noted above

**Comment by pbinkley** [comment]
I agree - we can fix that issue post-launch.

**Comment by nnunn** [comment]
@mbarnett thanks for catching that on the ui - I will fix it on the next code release.

**Pull request merged**
