### PR TITLE
Add fresh hard-coded item type counts for front page

### PR DESCRIPTION
**Pull request by pbinkley**
As a first step to #664, these numbers reflect the current state of migration plus the legacy theses.

### CODE REVIEW

**Comment by weiweishi** [comment]
the total count doesn't reflect the number with legacy thesis.

**Comment by pbinkley** [comment]
No, I didn't update the total. I'll do that.

**Comment by pbinkley** [comment]
And the other changes to custom.js shouldn't be there - must have messed up the copying between branches. Hang on.

**Comment by pbinkley** [comment]
Squashed the messy commits. It's as mergable as it's going to get.

**Pull request merged**
