### PR TITLE
Sprint 27

### PR DESCRIPTION
**Pull request by mbarnett**
Merge this once all PRs against sprint 27 are merged

### CODE REVIEW

**Comment by mbarnett** [comment]
@pgwillia and @pbinkley I think we should merge this and close and reopen the UI PRs against master instead, since they're holding all these other fixes up. Thoughts?

**Comment by pbinkley** [comment]
@nnunn has a fix in for the UI PR which @pgwillia is testing now, so we may be able to merge both...

**Comment by mbarnett** [comment]
aha, missed that latest update

**Comment by pgwillia** [comment]
specs running here too

**Comment by pgwillia** [comment]
2) collection total item count for a collection with 1 public item and 1 private item should be 2 when viewed by Jill, who owns the private item
     Failure/Error: item_count_node = page.find(:xpath, "//span[@itemprop='total_items']")
     Capybara::ElementNotFound:
       Unable to find xpath "//span[@itemprop='total_items']"
     # ./spec/features/collection/collection_spec.rb:43:in `block (3 levels) in <top (required)>'

  3) collection total item count for a collection with 1 public item and 1 private item should be 1 when viewed by Alice, who doesn't own the private item
     Failure/Error: item_count_node = page.find(:xpath, "//span[@itemprop='total_items']")
     Capybara::ElementNotFound:
       Unable to find xpath "//span[@itemprop='total_items']"
     # ./spec/features/collection/collection_spec.rb:51:in `block (3 levels) in <top (required)>'

**Pull request merged**
