### PR TITLE
Dataverse publisher

### LINKED ISSUE #492: Dataverse to HydraNorth: dcterms:publisher display
dcterms:publisher is not being displayed in plano
- example: http://plano.library.ualberta.ca/files/bv73ht029#.VZ2RaPlVhBc
(publisher: Population Research Laboratory)

Plan: 
- [x] add publisher field back into GenericFile, as it was in Sufia
- [x] add remote_resource attribute to GenericFile, and populate it in dataverse migration task: remote_resource='dataverse' - this allows us to identify imported dataverse items without depending on resource_type or membership in Dataverse collection
- [x] suppress publisher field in GenericFile editing form if remote_resource=='dataverse'

### PR DESCRIPTION
**Pull request by pbinkley**
Closes #492 
I've added a test record for a Dataverse item to spec/fixtures/migration/test-metadata/dataverse. This allows testing the searchability of the publisher field, and also allows a general test of the dataverse migration script. It will have to be updated as @johnhuck updates the Dataverse export process.
I've implemented the publisher field as a second-class citizen: it is not in the metadata form or advanced search, and it is not faceted. It is only used to display on the single-item view for Dataverse items. It is indexed as facetable, however, to enable the view to be presented as a search link to gather other items by the same publisher.

### CODE REVIEW

**Comment by pbinkley** [comment]
Hold off on merging this one - John came up with one more idea.

**Comment by pbinkley** [comment]
Go ahead and merge - no change needed.

**Comment by sfarnel** [comment]
In future we will need the publisher field to be able to be a first class
citizen but that can come later.

On Thu, Jul 23, 2015 at 10:16 AM, Peter Binkley <notifications@github.com>
wrote:

> Go ahead and merge - no change needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/pull/532#issuecomment-124155056>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
Had two failed tests. I'm looking into this. 

Failures:

  1) Migration rake tasks migration:dataverse dataverse item should be migrated
     Failure/Error: expect(subject.remote_resource).to eq "dataverse"

       expected: "dataverse"
            got: nil

       (compared using ==)
     # ./spec/tasks/dataverse_migration_rake_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) Migration rake tasks migration:dataverse catalog searching should find item by publisher
     Failure/Error: click_link('Shape File Index to the Sectional Maps, 1917 [of Western Canada, new style, 1905-1955].')
     Capybara::ElementNotFound:
       Unable to find link "Shape File Index to the Sectional Maps, 1917 [of Western Canada, new style, 1905-1955]."
     # ./spec/tasks/dataverse_migration_rake_spec.rb:32:in `block (4 levels) in <top (required)>'

**Comment by pbinkley** [comment]
​​That looks like the object failed to import. The remote_resource
attribute is added along with all the other file_attributes:
https://github.com/ualbertalib/HydraNorth/blob/dataverse_publisher/lib/tasks/dataverse_migration.rake#L137
.

Failed imports often happened to me when I did a jetty:clean and then
forgot to reseed to create the "Dataverse Datasets" collection. I worked
around this in the spec by using a factory to create this collection, but
maybe something is going wrong there.

https://github.com/ualbertalib/HydraNorth/blob/dataverse_publisher/spec/tasks/dataverse_migration_rake_spec.rb#L5

Peter

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
The migration was failed because of the lack of collection. FactoryGirl.create (or FactoryGirl.new) doesn't seem to create a new collection and save it back into Solr and Fedora. 

I've changed the initiation of dataverse_collection in the spec file:
```ruby
  let(:dataverse_collection) do
    Collection.create(title: 'Dataverse Datasets') do |c|
      c.apply_depositor_metadata(FactoryGirl.create(:dit).user_key)
      c.save
    end
  end
```
And I've put in the following in the migration script around line 143 to create the collection if it doesn't exist:
```ruby
      dataverse_dataset = Collection.find_with_conditions('title' => 'Dataverse Datasets')
      if !dataverse_dataset.present?
        c = Collection.new('title'=> 'Dataverse Datasets')
        c.apply_depositor_metadata("dit.application.test@ualberta.ca")
        c.save!
        id = c.id
      else
        id = dataverse_dataset.first['id']
      end
```

All tests are passed on local VM but timed out in Travis.

**Pull request merged**
