### PR TITLE
962 collection landing page

### PR DESCRIPTION
**Pull request by criedlberger**

### CODE REVIEW

**Comment by pbinkley** [comment]
I'm getting 

```Showing /var/www/sites/hydranorth/app/views/collections/_show_document_list.html.erb where line #13 raised:
undefined local variable or method `documents' for #<#<Class:0x00000006ed2c80>:0x00000006df6988>```

when I visit a collection page like ```https://hydranorthdev.library.ualberta.ca/collections/dz010q04x```. Is some change missing from the PR?

**Comment by pbinkley** [comment]
The error in the previous comment doesnt' happen when this branch is merged into master. I do get these failed specs though (which pass in master):

```
Finished in 28 minutes 28 seconds (files took 10.47 seconds to load)
380 examples, 5 failures, 2 pending

Failed examples:

rspec ./spec/features/collection/1008_users_shouldnt_see_edit_collection_spec.rb:41 # collection admin should not be able to see edit for admin collection
rspec ./spec/features/collection/1008_users_shouldnt_see_edit_collection_spec.rb:45 # collection admin should not be able to see edit for official collection
rspec ./spec/features/collection/collection_spec.rb:177 # collection show collection as admin should allow me to nest collections
rspec ./spec/features/collection/collection_spec.rb:258 # collection delete items from collection should add and delete item from collection
rspec ./spec/features/collection/collection_spec.rb:321 # collection create collection should be able to create a collection
```

**Comment by criedlberger** [comment]
@pbinkley added a couple of files which had changes which I did not add to the original PR

**Comment by pbinkley** [comment]
OK, it's good now.

**Comment by pbinkley** [comment]
I've merged this PR into the Sprint38 branch, as we discussed at last week's sprint wrap-up.

**Comment by weiweishi** [comment]
This has not been merged into Sprint38? I can't find the code there? @pbinkley what's the history for reopening the issue?
If that's the case, @criedlberger could you please submit another PR for Sprint38 branch?

Thanks!

**Comment by weiweishi** [comment]
superseded by #1029. PR on Sprint38 branch instead of master.

**Pull request closed without merging**
