### PR TITLE
Saml

### PR DESCRIPTION
**Pull request by pgwillia**
Will continue to add to SAML branch. Work to date is ready to merge.

### CODE REVIEW

**Comment by pgwillia** [comment]
We decided to leave this PR open until all the parts to SAML are implemented

**Comment by pgwillia** [comment]
This should be mergable and completes the workflow for #428.  @weiweishi want to take a look?

**Comment by weiweishi** [comment]
@pgwillia Wonderful! Will do.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pgwillia** [comment]
Should I squash the commits so there is only one?

**Comment by weiweishi** [comment]
No I'd prefer to leave the commit history with reference to individual scenarios so that it's will be easier for us to track the changes. @pgwillia what do you think?

**Comment by pgwillia** [comment]
That's fine. I could go either way. Leaving the multiple commits for this feature.

**Comment by pbinkley** [comment]
I agree - where different commits close different issues, it makes sense to me to keep that as part of the history.

**Comment by weiweishi** [comment]
get the follow error message when doing this:
image

image

**Comment by weiweishi** [comment]
I've restarted httpd but still got the same error message. 
What I did:
git checkout saml
bundle install
bundle exec rake db:migrate
service httpd restart

Anything I missed?

**Comment by weiweishi** [comment]
The previous error was gone after I built a new VM. 

Seeing issue with SAML 1:
* created a new account as alterego@testshib.org with regular sign-in process. 
* logged out with the account. 
* logged in with Shibboleth Id alterego on testshib through "Sign in with Shibboleth"
* able to login. However when going to Edit Profile, still seeing "Link CCID credentials to account" and not seeing "linked" message. The shibboleth info was not added to the database. 
[]  Then the account with the same email should be updated with shibboleth provider on #457 doesn't seem to be there?

**Comment by mbarnett** [comment]
Will do

**Comment by mbarnett** [comment]
This should now be fixed.

**Comment by weiweishi** [comment]
Seeing 2 failing rspec tests:
Failures:

  1) generic file new request CSTR item should have CSTR field
     Failure/Error: expect(page).to have_css('input#generic_file_trid')
       expected to find css "input#generic_file_trid" but there were no matches
     # ./spec/forms/generic_file_new_form_spec.rb:40:in `block (3 levels) in <top (required)>'

  2) Migration rake tasks migration:dataverse dataverse item should be migrated
     Failure/Error: expect(subject.remote_resource).to eq "dataverse"

       expected: "dataverse"
            got: nil

       (compared using ==)
     # ./spec/tasks/dataverse_migration_rake_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 22 minutes 39 seconds (files took 1 minute 27.77 seconds to load)
210 examples, 2 failures

Failed examples:

rspec ./spec/forms/generic_file_new_form_spec.rb:30 # generic file new request CSTR item should have CSTR field
rspec ./spec/tasks/dataverse_migration_rake_spec.rb:27 # Migration rake tasks migration:dataverse dataverse item should be migrated

But I don't think they are related. I will fix the tests in a different branch. Go ahead and merging this PR.

**Pull request merged**
