### PR TITLE
Sprint41

### LINKED ISSUE #850: Google Scholar Indexing (3): Browse by date
Issue 3 of Epic #435.

With reference to UAL's [Google Scholar Strategy document] (https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s).

Ensure that ERA content is crawl-able by ensuring that we have a suitable 'browse by date' interface, as recommended in the inclusion guidelines (and perhaps configure exclusions appropriately in the robot.txt file).

https://scholar.google.com/intl/en/scholar/inclusion.html#crawl

B. If your website has thousands of papers or more, the best way to make sure they're all discovered by the search robots is to provide a way to list them by the date of publication or the date of record entry. Other forms of browse interfaces, such as browse by author or by keyword, often generate more URLs than your website can deliver to the search robots in a reasonable amount of time.

C. For websites with more than a hundred thousand papers, we recommend that you create an additional browse interface that lists only the articles added in the last two weeks. This smaller set of webpages can be recrawled more frequently than your entire browse interface, which will facilitate timely coverage of your recent papers by the search robots.

### PR DESCRIPTION
**Pull request by pbinkley**
All specs are passing. I set one to pending, which requires new test metadata. Mariana sent me a new version which should work but it created other issues. Since it only affects migrating theses from old ERA, I'll put in an issue to fix it and move ahead with this branch.

Closes #850
#986
#1056
#962 #961

### CODE REVIEW

**Comment by pgwillia** [comment]
There is something up with hasCollection -- not being stored.  Trying to find out where this might have been changed.

```
Failures:

  1) Collection should not insert a hasCollection_ref instead of hasCollection
     Failure/Error: expect(xml.xpath(%Q|//sv:property[@sv:name="#{namespace}:hasCollection"]|)).not_to be_empty
       expected `[].empty?` to return false, got true
     # ./spec/models/collection_spec.rb:104:in `block (2 levels) in <top (required)>'

```

**Comment by leahvanderjagt** [comment]
I just had a user report a problem with disappearing collections in the
drop-down/deposit and I also had a problem with community/collection
yesterday when I edited an item (the community and collection disappeared
from the display for edit). I'm trying to assess the issue from the user
end. Could this be connected somehow?

Leah

On Fri, May 20, 2016 at 9:22 AM, pgwillia <notifications@github.com> wrote:

> There is something up with hasCollection -- not being stored. Trying to
> find out where this might have been changed.
>
> Failures:
>
>   1) Collection should not insert a hasCollection_ref instead of hasCollection
>      Failure/Error: expect(xml.xpath(%Q|//sv:property[@sv:name="#{namespace}:hasCollection"]|)).not_to be_empty
>        expected `[].empty?` to return false, got true
>      # ./spec/models/collection_spec.rb:104:in `block (2 levels) in <top (required)>'
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220636106>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pgwillia** [comment]
I'm working on unreleased and undeployed code, so I really hope they're not
related.

**Comment by leahvanderjagt** [comment]
OK, that's good.

I'll enter the bugs I've noticed as a new issue right away

Leah

On Fri, May 20, 2016 at 9:33 AM, pgwillia <notifications@github.com> wrote:

> I'm working on unreleased and undeployed code, so I really hope they're not
> related.
>
> On Fri, May 20, 2016 at 9:31 AM, leahvanderjagt <notifications@github.com>
> wrote:
>
> > I just had a user report a problem with disappearing collections in the
> > drop-down/deposit and I also had a problem with community/collection
> > yesterday when I edited an item (the community and collection disappeared
> > from the display for edit). I'm trying to assess the issue from the user
> > end. Could this be connected somehow?
> >
> > Leah
> >
> > On Fri, May 20, 2016 at 9:22 AM, pgwillia <notifications@github.com>
> > wrote:
> >
> > > There is something up with hasCollection -- not being stored. Trying to
> > > find out where this might have been changed.
> > >
> > > Failures:
> > >
> > > 1) Collection should not insert a hasCollection_ref instead of
> > hasCollection
> > > Failure/Error:
> >
> expect(xml.xpath(%Q|//sv:property[@sv:name="#{namespace}:hasCollection"]|)).not_to
> > be_empty
> > > expected `[].empty?` to return false, got true
> > > # ./spec/models/collection_spec.rb:104:in `block (2 levels) in <top
> > (required)>'
> > >
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220636106
> > >
> > >
> >
> >
> >
> > --
> > ___________________________________________________________
> >
> >
> >
> >
> > *Leah VanderjagtDigital Repository Services Librarian University of
> > Albertat. 780.492.3851 *
> > *leahv@ualberta.ca <leahv@ualberta.ca> *
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220638484
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220639003>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
I saw that hasCollection_ref error in the specs yesterday but it stopped
with 74bc370 . I assumed it was a side-effect of the failure of that spec,
since I couldn't reproduce it after that, but now that I look at it that
doesn't make much sense.

Peter

**Comment by pbinkley** [comment]
Leah, those bugs will almost certainly be fixed when Matt's big Collection
PR goes in, but it's good to have them tracked.

**Comment by leahvanderjagt** [comment]
No, this is a new problem.

On Fri, May 20, 2016 at 9:38 AM, Peter Binkley <notifications@github.com>
wrote:

> Leah, those bugs will almost certainly be fixed when Matt's big Collection
> PR goes in, but it's good to have them tracked.
>
>
> On 20 May 2016 at 09:34, leahvanderjagt <notifications@github.com> wrote:
>
> > OK, that's good.
> >
> > I'll enter the bugs I've noticed as a new issue right away
> >
> > Leah
> >
> >
> > On Fri, May 20, 2016 at 9:33 AM, pgwillia <notifications@github.com>
>
> > wrote:
> >
> > > I'm working on unreleased and undeployed code, so I really hope they're
> > not
> > > related.
> > >
> > > On Fri, May 20, 2016 at 9:31 AM, leahvanderjagt <
> > notifications@github.com>
> > > wrote:
> > >
> > > > I just had a user report a problem with disappearing collections in
> the
> > > > drop-down/deposit and I also had a problem with community/collection
> > > > yesterday when I edited an item (the community and collection
> > disappeared
> > > > from the display for edit). I'm trying to assess the issue from the
> > user
> > > > end. Could this be connected somehow?
> > > >
> > > > Leah
> > > >
> > > > On Fri, May 20, 2016 at 9:22 AM, pgwillia <notifications@github.com>
> > > > wrote:
> > > >
> > > > > There is something up with hasCollection -- not being stored.
> Trying
> > to
> > > > > find out where this might have been changed.
> > > > >
> > > > > Failures:
> > > > >
> > > > > 1) Collection should not insert a hasCollection_ref instead of
> > > > hasCollection
> > > > > Failure/Error:
> > > >
> > >
> >
> expect(xml.xpath(%Q|//sv:property[@sv:name="#{namespace}:hasCollection"]|)).not_to
> > > > be_empty
> > > > > expected `[].empty?` to return false, got true
> > > > > # ./spec/models/collection_spec.rb:104:in `block (2 levels) in <top
> > > > (required)>'
> > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220636106
> > > > >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > ___________________________________________________________
> > > >
> > > >
> > > >
> > > >
> > > > *Leah VanderjagtDigital Repository Services Librarian University of
> > > > Albertat. 780.492.3851 *
> > > > *leahv@ualberta.ca <leahv@ualberta.ca> *
> > > >
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220638484
> > > >
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220639003
> > >
> > >
> >
> >
> >
> > --
> > ___________________________________________________________
> >
> >
> >
> >
> > *Leah VanderjagtDigital Repository Services Librarian University of
> > Albertat. 780.492.3851 *
> > *leahv@ualberta.ca <leahv@ualberta.ca> *
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220639303
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220640558>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by leahvanderjagt** [comment]
What I mean to say is: the problems I am seeing have at least in part been
addressed previously. However, I have not encountered a situation where a
community lost one of its collections. I'll finish entering the issue. One
moment please -

On Fri, May 20, 2016 at 9:40 AM, Leah Vanderjagt <leahv@ualberta.ca> wrote:

> No, this is a new problem.
>
> On Fri, May 20, 2016 at 9:38 AM, Peter Binkley <notifications@github.com>
> wrote:
>
>> Leah, those bugs will almost certainly be fixed when Matt's big Collection
>> PR goes in, but it's good to have them tracked.
>>
>>
>> On 20 May 2016 at 09:34, leahvanderjagt <notifications@github.com> wrote:
>>
>> > OK, that's good.
>> >
>> > I'll enter the bugs I've noticed as a new issue right away
>> >
>> > Leah
>> >
>> >
>> > On Fri, May 20, 2016 at 9:33 AM, pgwillia <notifications@github.com>
>>
>> > wrote:
>> >
>> > > I'm working on unreleased and undeployed code, so I really hope
>> they're
>> > not
>> > > related.
>> > >
>> > > On Fri, May 20, 2016 at 9:31 AM, leahvanderjagt <
>> > notifications@github.com>
>> > > wrote:
>> > >
>> > > > I just had a user report a problem with disappearing collections in
>> the
>> > > > drop-down/deposit and I also had a problem with community/collection
>> > > > yesterday when I edited an item (the community and collection
>> > disappeared
>> > > > from the display for edit). I'm trying to assess the issue from the
>> > user
>> > > > end. Could this be connected somehow?
>> > > >
>> > > > Leah
>> > > >
>> > > > On Fri, May 20, 2016 at 9:22 AM, pgwillia <notifications@github.com
>> >
>> > > > wrote:
>> > > >
>> > > > > There is something up with hasCollection -- not being stored.
>> Trying
>> > to
>> > > > > find out where this might have been changed.
>> > > > >
>> > > > > Failures:
>> > > > >
>> > > > > 1) Collection should not insert a hasCollection_ref instead of
>> > > > hasCollection
>> > > > > Failure/Error:
>> > > >
>> > >
>> >
>> expect(xml.xpath(%Q|//sv:property[@sv:name="#{namespace}:hasCollection"]|)).not_to
>> > > > be_empty
>> > > > > expected `[].empty?` to return false, got true
>> > > > > # ./spec/models/collection_spec.rb:104:in `block (2 levels) in
>> <top
>> > > > (required)>'
>> > > > >
>> > > > >
>> > > > > —
>> > > > > You are receiving this because you are subscribed to this thread.
>> > > > > Reply to this email directly or view it on GitHub
>> > > > > <
>> > > >
>> > >
>> >
>> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220636106
>> > > > >
>> > > > >
>> > > >
>> > > >
>> > > >
>> > > > --
>> > > > ___________________________________________________________
>> > > >
>> > > >
>> > > >
>> > > >
>> > > > *Leah VanderjagtDigital Repository Services Librarian University of
>> > > > Albertat. 780.492.3851 *
>> > > > *leahv@ualberta.ca <leahv@ualberta.ca> *
>> > > >
>> > > > —
>> > > > You are receiving this because you commented.
>> > > > Reply to this email directly or view it on GitHub
>> > > > <
>> > >
>> >
>> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220638484
>> > > >
>> > > >
>> > >
>> > > —
>> > > You are receiving this because you commented.
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220639003
>> > >
>> > >
>> >
>> >
>> >
>> > --
>> > ___________________________________________________________
>> >
>> >
>> >
>> >
>> > *Leah VanderjagtDigital Repository Services Librarian University of
>> > Albertat. 780.492.3851 *
>> > *leahv@ualberta.ca <leahv@ualberta.ca> *
>> >
>> > —
>> > You are receiving this because you authored the thread.
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220639303
>> >
>> >
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/pull/1102#issuecomment-220640558>
>>
>
>
>
> --
> ___________________________________________________________
>
>
>
>
> *Leah VanderjagtDigital Repository Services Librarian University of
> Albertat. 780.492.3851 <780.492.3851> *
> *leahv@ualberta.ca <leahv@ualberta.ca> *
>
>


-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pgwillia** [comment]
Turns out @mbarnett commit 432046c2ce008cb566d3c1df19a752bc9a4ead75 should trump @pgwillia commit 91ec9c4974da364e3821c403336018951ffbb551.

**Pull request merged**
