### PR TITLE
fix issue with the server issuing 500s when records aren't found

### PR DESCRIPTION
**Pull request by mbarnett**
Right now the server 500s if you try to visit an item it can't find, eg) https://hydranorth.library.ualberta.ca/files/asdfg

This is suboptimal behaviour, so this commit rescues ActiveFedora and ActiveRecord not found errors properly so that we can render a human-friendly 404 page (and send the correct 404 status code to robots and other forms of life).

There's no issue associated with this, I just noticed it while fixing another issue, and it's annoying.

### CODE REVIEW

**Comment by mbarnett** [comment]
WIP. Don't merge this yet. Waiting on wording from @sfbetz

**Comment by sfbetz** [comment]
Language for 404 (we will need to update again after migration is complete):

The item you are looking for is not currently available in ERA. We are migrating our collections and it will take a few days for all the items to appear. Please contact us at erahelp@ualberta.ca if you would like more information about this migration.

**Comment by mbarnett** [comment]
@sfbetz for your approval:

**Comment by sfbetz** [comment]
Perfect! Thanks

**Comment by sfbetz** [comment]
Wait! Footer is old footer still too.... will that update on production, or does some manual magic need to happen?

**Comment by sfbetz** [comment]
Ignore last comment - forgot that we haven't yet deployed new content for footer...

**Comment by mbarnett** [comment]
Ignoring like a pro

**Pull request closed without merging**
