### PR TITLE
Migration handle update

### PR DESCRIPTION
**Pull request by weiweishi**
-     allow migration process to decode html encodings such as & amp;
-     update the script so that it will update handles in production to redirect to ERA
-     generate noid report at the end of the migration process.
-     added the new graduation date to allow editing in UI
This is related #528 as it can be solution with same script and strategy if needed.

### CODE REVIEW

**Comment by weiweishi** [comment]
@pgwillia I messed up with the commit history in the other PR #1190 So I've created this new one. Please let me know if I have addressed all the concerns you have. Thanks!

**Comment by pgwillia** [comment]
@weiweishi did you follow up with @henryzhang87 about installing the handle cli from the playbook? This is the only part I'm still concerned about. Shall I merge as is and create a technical maintenance ticket to ensure that this will fail gracefully? I don't think this even reports failure at the moment.

**Comment by pgwillia** [comment]
Otherwise I think this looks good :+1:

**Comment by weiweishi** [comment]
@pbinkley @mbarnett this is ready now.

**Pull request merged**
